version: '2'

services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/armhf-homeassistant:0.85.1
    volumes:
      - /opt/has/config:/config
      - /etc/localtime:/etc/localtime:ro
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: on-failure:3
    network_mode: host
    user: has
    depends_on:
      - mariadb
      - influxdb
  mariadb:
    container_name: mariadb
    image: yobasystems/alpine-mariadb:armhf
    volumes:
      - /opt/mariadb/data:/var/lib/mysql
      - /opt/mariadb/config:/etc/mysql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3306:3306"
    restart: on-failure:3
    network_mode: bridge
    user: has
  influxdb:
    container_name: influxdb
    image: influxdb:3
    ports:
      - "8086:8086"
    volumes:
      - /opt/has/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
      - /opt/has/influxdb:/var/lib/influxdb
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure
    network_mode: bridge
    user: has
  grafana:
    container_name: grafana
    image:  proxx/grafana-armv7
    ports:
      - "3000:3000"
    volumes:
    #  - /opt/has/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /etc/localtime:/etc/localtime:ro
    restart: on-failure:3
    network_mode: bridge
    depends_on:
      - influxdb
    user: has
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/has/mqtt/conf:/mosquitto/config
      - /opt/has/mqtt/data:/mosquitto/data
      - /opt/has/mqtt/logs:/mosquitto/log
    restart: on-failure:3
    network_mode: bridge
    ports:
      - "1883:1883"
    user: has
